name: galleryapp
description: A new Flutter application.
version: 1.17.0
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.0
  provider: ^4.0.5
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
